CREATE TABLE MOVIE_SESSIONS(
ID SERIAL,
DATETIME TIMESTAMP,
MOVIE_ID INT,
HALL_ID INT,
TARIFF_ID INT,
STATUS CHAR(1),
INSSTMP TIMESTAMP,
UPDSTMP TIMESTAMP
);

CREATE TABLE MOVIES(
ID SERIAL,
NAME VARCHAR(100),
DURATION VARCHAR(10),
STATUS CHAR(1),
INSSTMP TIMESTAMP,
UPDSTMP TIMESTAMP
);